baseURL = "http://www.mg-ecoconstruction.com/"
ignoreFiles = [ "static-src" ]
languageCode = "fr-FR"
theme = "mgeco"
title = "MG Éco-construction"

[params]
  corporateName = "SAS MG ECO"
  casualName = "MG Éco"
  address0 = "32 rue des alisiers"
  address1 = "route de Cénevières"
  address2 = "46260 LIMOGNE EN QUERCY"
  postalCode = "46260"
  locality = "Limogne en Quercy"
  phoneLandline = "05 65 21 73 08"
  phoneMobile = "06 74 66 08 92"
  email = "contact@mg-ecoconstruction.com"
  rcs = "RCS CAHORS 538 164 120"
  activite = "Constructions écologiques"
  activites = "Ossature bois, maison paille, charpente, couverture, isolation, rénovation, conception de plans, étude thermique"

  [params.liens]
    RGE = "http://www.developpement-durable.gouv.fr/La-mention-RGE-Reconnu-Garant-de-l.html"
    mapURL = "https://www.google.com/maps/place/32+Rue+des+Alisiers,+46260+Limogne-en-Quercy,+France/@44.3977773,1.7649764,15z/data=!4m5!3m4!1s0x12acff40b55922a1:0x96ac1ec021e3b1b5!8m2!3d44.403363!4d1.7685394?hl=fr-FR"
    mapURLembedded = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11402.371029317148!2d1.7634311336899378!3d44.400480880314205!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12acff40b55922a1%3A0x96ac1ec021e3b1b5!2s32+Rue+des+Alisiers%2C+46260+Limogne-en-Quercy%2C+France!5e0!3m2!1sfr!2sfr!4v1498260071808"
