# Toutes les images sont implicitement des .jpg
carousel = [33, 8, 15, 40, 1]
[[gallery]]
  [[gallery.image]]
    1 = "Maison roulotte à Cahors"
  [[gallery.image]]
    2 = "Bardage mélèze couvre-joints"
  [[gallery.image]]
    3 = "Maison roulotte à Cahors"
  [[gallery.image]]
    4 = "Terrasse extérieure : plancher chêne"
  [[gallery.image]]
    5 = "Toiture zinc à joints de bout"
  [[gallery.image]]
    6 = "Une image"
  [[gallery.image]]
    7 = "Une image"
  [[gallery.image]]
    8 = "Une image"
  [[gallery.image]]
    9 = "Une image"
  [[gallery.image]]
    10 = "Une image"
  [[gallery.image]]
    11 = "Une image"
  [[gallery.image]]
    12 = "Une image"
  [[gallery.image]]
    13 = "Une image"
  [[gallery.image]]
    14 = "Une image"
  [[gallery.image]]
    15 = "Une image"
  [[gallery.image]]
    16 = "Une image"
  [[gallery.image]]
    17 = "Une image"
  [[gallery.image]]
    18 = "Une image"
  [[gallery.image]]
    19 = "Une image"
  [[gallery.image]]
    20 = "Une image"
  [[gallery.image]]
    21 = "Une image"
  [[gallery.image]]
    22 = "Une image"
  [[gallery.image]]
    23 = "Une image"
  [[gallery.image]]
    24 = "Une image"
  [[gallery.image]]
    25 = "Une image"
  [[gallery.image]]
    26 = "Une image"
  [[gallery.image]]
    27 = "Une image"
  [[gallery.image]]
    28 = "Une image"
  [[gallery.image]]
    29 = "Une image"
  [[gallery.image]]
    30 = "Une image"
  [[gallery.image]]
    31 = "Une image"
  [[gallery.image]]
    32 = "Une image"
  [[gallery.image]]
    33 = "Une image"
  [[gallery.image]]
    34 = "Une image"
  [[gallery.image]]
    35 = "Une image"
  [[gallery.image]]
    36 = "Une image"
  [[gallery.image]]
    37 = "Une image"
  [[gallery.image]]
    38 = "Une image"
  [[gallery.image]]
    39 = "Une image"
  [[gallery.image]]
    40 = "Une image"
  [[gallery.image]]
    41 = "Une image"
  [[gallery.image]]
    42 = "Une image"
  [[gallery.image]]
    43 = "Une image"
  [[gallery.image]]
    44 = "Une image"
  [[gallery.image]]
    45 = "Une image"
  [[gallery.image]]
    46 = "Une image"
  [[gallery.image]]
    47 = "Une image"
  [[gallery.image]]
    48 = "Une image"
  [[gallery.image]]
    49 = "Une image"
  [[gallery.image]]
    50 = "Une image"
  [[gallery.image]]
    51 = "Une image"
  [[gallery.image]]
    52 = "Une image"
  [[gallery.image]]
    53 = "Une image"
  [[gallery.image]]
    54 = "Une image"
  [[gallery.image]]
    55 = "Une image"
  [[gallery.image]]
    56 = "Une image"
  [[gallery.image]]
    57 = "Une image"
  [[gallery.image]]
    58 = "Une image"
  [[gallery.image]]
    59 = "Une image"
  [[gallery.image]]
    60 = "Une image"
  [[gallery.image]]
    61 = "Une image"
  [[gallery.image]]
    62 = "Une image"
  [[gallery.image]]
    63 = "Une image"
  [[gallery.image]]
    64 = "Une image"
  [[gallery.image]]
    65 = "Une image"
  [[gallery.image]]
    66 = "Une image"
  [[gallery.image]]
    67 = "Une image"
  [[gallery.image]]
    68 = "Une image"
  [[gallery.image]]
    69 = "Une image"
  [[gallery.image]]
    70 = "Une image"
  [[gallery.image]]
    71 = "Une image"
  [[gallery.image]]
    72 = "Une image"
  [[gallery.image]]
    73 = "Une image"
  [[gallery.image]]
    74 = "Une image"
  [[gallery.image]]
    75 = "Une image"
  [[gallery.image]]
    76 = "Une image"
  [[gallery.image]]
    77 = "Une image"
  [[gallery.image]]
    78 = "Une image"
  [[gallery.image]]
    79 = "Une image"
  [[gallery.image]]
    80 = "Une image"
  [[gallery.image]]
    81 = "Une image"
  [[gallery.image]]
    82 = "Une image"
  [[gallery.image]]
    83 = "Une image"
  [[gallery.image]]
    84 = "Une image"
  [[gallery.image]]
    85 = "Une image"
  [[gallery.image]]
    86 = "Une image"
  [[gallery.image]]
    87 = "Une image"
  [[gallery.image]]
    88 = "Une image"
  [[gallery.image]]
    89 = "Une image"
  [[gallery.image]]
    90 = "Une image"
  [[gallery.image]]
    91 = "Une image"
  [[gallery.image]]
    92 = "Une image"
  [[gallery.image]]
    93 = "Une image"
  [[gallery.image]]
    94 = "Une image"
  [[gallery.image]]
    95 = "Une image"
  [[gallery.image]]
    96 = "Une image"
  [[gallery.image]]
    97 = "Une image"
  [[gallery.image]]
    98 = "Une image"
  [[gallery.image]]
    99 = "Une image"
