carousel = [33, 8, 15, 40, 1]
[gallery]
  1 = "Maison roulotte à Cahors"
  2 = "Bardage mélèze couvre-joints"
  3 = "Maison roulotte à Cahors"
  4 = "Terrasse extérieure : plancher chêne"
  5 = "Toiture zinc à joints de bout"
